#!/bin/env python3

import os
from configparser import ConfigParser
from git import Repo
from orbit import DP

START_TEMPLATE="""
[uwsgi]
socket = localhost:%s
wsgi-file = app.py
processes = 4
threads = 2
""".strip()
# skipping stats server for now

# TODO dependency on gitpython

# quick and dirty: load authority server from auth_server file generated by genginx.py
auth_server=''
try:
    with open('auth_server', 'r') as f:
        auth_server = f.read()
except:
    DP('no auth_server file found? Run genginx.py first or create it manually')

parser = ConfigParser()

parser.read('kdlp.ini')

planets = parser['planets']


for planet in planets:
    _plan = parser[planet]
    config = ''
    print('#####')
    print('APPLICATION = %s' % planet)
    print('VERSION = %s' % _plan.get('ver'))
    print('SOURCE = %s' % planets[planet])

    config += "APPLICATION = '%s'\n" % planet
    config += "VERSION = '%s'\n" % _plan.get('ver')
    config += "SOURCE = '%s'\n" % planets[planet]
    source = planets[planet]

    # don't bother with version until this stabilizes
    #ver = planet[ver]
    repo = Repo.clone_from(source, planet)
    config += "ROOT = '%s'\n" % (os.getcwd() + '/root')
    config += "AUTH_SERVER = '%s'\n" % auth_server
    # here we would check out the right version but don't bother for now

    # install the new config and common library
    with open('orbit.py', 'r') as file:
        filedata = file.read()

    filedata = filedata.replace('###@REPLACE@###', config)

    with open(planet + '/orbit.py', 'w') as file:
        file.write(filedata)

    start_ini = START_TEMPLATE % _plan.get('port')
    # bad hack to make auth server run over http
    # should not hardcode this but I'm doing it anyway for now
    # FIXME
    if planet == 'venus':
        start_ini = start_ini.replace('socket', 'http')
    with open(planet + '/start.ini', 'w') as file:
        file.write(start_ini)



root = parser['root']
print('#### root ####')
print('source = %s' % root.get('source'))
print('ver = %s' % root.get('ver'))
print('headers = %s' % root.get('headers'))

root_source = root.get('source')
root_ver = root.get('ver')

repo = Repo.clone_from(root_source, 'root')
repo.head.reference = repo.create_head(root_ver, 'origin/' + root_ver)
repo.head.reset(index=True, working_tree=True)

